// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb_rY4oPCYQ8iGLslhYsFxbndBWQ-sNhc',
    appId: '1:419219079844:web:73528bf490a35561b71c31',
    messagingSenderId: '419219079844',
    projectId: 'notes-e45df',
    authDomain: 'notes-e45df.firebaseapp.com',
    storageBucket: 'notes-e45df.firebasestorage.app',
    measurementId: 'G-6G54KXFYHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB66x-fy065fS13UZNrlAzG-xfKGHaGXQ4',
    appId: '1:419219079844:android:efb31d4dbd6027b3b71c31',
    messagingSenderId: '419219079844',
    projectId: 'notes-e45df',
    storageBucket: 'notes-e45df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7o4Mi_ZwQEvvObvqiYAnI1o8OU74TAoM',
    appId: '1:419219079844:ios:7cb42844a91bf60ab71c31',
    messagingSenderId: '419219079844',
    projectId: 'notes-e45df',
    storageBucket: 'notes-e45df.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7o4Mi_ZwQEvvObvqiYAnI1o8OU74TAoM',
    appId: '1:419219079844:ios:7cb42844a91bf60ab71c31',
    messagingSenderId: '419219079844',
    projectId: 'notes-e45df',
    storageBucket: 'notes-e45df.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb_rY4oPCYQ8iGLslhYsFxbndBWQ-sNhc',
    appId: '1:419219079844:web:1d8211a6b6506aaab71c31',
    messagingSenderId: '419219079844',
    projectId: 'notes-e45df',
    authDomain: 'notes-e45df.firebaseapp.com',
    storageBucket: 'notes-e45df.firebasestorage.app',
    measurementId: 'G-2NG6HT85BL',
  );
}
