// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjC6zzgTaa9FoWvU4VTX-1Ncgu7ZFZzCo',
    appId: '1:361172399073:web:8394a8c8ac9e3bf78258a0',
    messagingSenderId: '361172399073',
    projectId: 'daftarbelanja-236b5',
    authDomain: 'daftarbelanja-236b5.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-236b5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-236b5.firebasestorage.app',
    measurementId: 'G-G8WMJ09GJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaISyo_S5YtzX1A-ZVyex9dvyoOny0Plw',
    appId: '1:361172399073:android:436d60fc2d234c588258a0',
    messagingSenderId: '361172399073',
    projectId: 'daftarbelanja-236b5',
    databaseURL: 'https://daftarbelanja-236b5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-236b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAupVcNQ8cFuH7SQ_kNaWgF8slOcMPhJ2M',
    appId: '1:361172399073:ios:b5edc939a81dddb78258a0',
    messagingSenderId: '361172399073',
    projectId: 'daftarbelanja-236b5',
    databaseURL: 'https://daftarbelanja-236b5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-236b5.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAupVcNQ8cFuH7SQ_kNaWgF8slOcMPhJ2M',
    appId: '1:361172399073:ios:b5edc939a81dddb78258a0',
    messagingSenderId: '361172399073',
    projectId: 'daftarbelanja-236b5',
    databaseURL: 'https://daftarbelanja-236b5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-236b5.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjC6zzgTaa9FoWvU4VTX-1Ncgu7ZFZzCo',
    appId: '1:361172399073:web:c697e9f8472653dc8258a0',
    messagingSenderId: '361172399073',
    projectId: 'daftarbelanja-236b5',
    authDomain: 'daftarbelanja-236b5.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-236b5-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-236b5.firebasestorage.app',
    measurementId: 'G-J8GDP9YS38',
  );
}
