// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXuC3lw865eAVxwuQIgfmNQDm790X9rYI',
    appId: '1:832443292148:web:caef808603f03020e5c1a1',
    messagingSenderId: '832443292148',
    projectId: 'belajar-uts-9dd07',
    authDomain: 'belajar-uts-9dd07.firebaseapp.com',
    databaseURL: 'https://belajar-uts-9dd07-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-uts-9dd07.firebasestorage.app',
    measurementId: 'G-JTQ8N7F1VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYPLi7dwPm7LhO5CWaGEPrdJ199pTHpo',
    appId: '1:832443292148:android:04ad6b95dc363bc3e5c1a1',
    messagingSenderId: '832443292148',
    projectId: 'belajar-uts-9dd07',
    databaseURL: 'https://belajar-uts-9dd07-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-uts-9dd07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF9ipdI9lcsKwfNJZo6efl9LebYJdtv5Y',
    appId: '1:832443292148:ios:db548e5114136a8ee5c1a1',
    messagingSenderId: '832443292148',
    projectId: 'belajar-uts-9dd07',
    databaseURL: 'https://belajar-uts-9dd07-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-uts-9dd07.firebasestorage.app',
    iosBundleId: 'com.example.belajarUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF9ipdI9lcsKwfNJZo6efl9LebYJdtv5Y',
    appId: '1:832443292148:ios:db548e5114136a8ee5c1a1',
    messagingSenderId: '832443292148',
    projectId: 'belajar-uts-9dd07',
    databaseURL: 'https://belajar-uts-9dd07-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-uts-9dd07.firebasestorage.app',
    iosBundleId: 'com.example.belajarUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXuC3lw865eAVxwuQIgfmNQDm790X9rYI',
    appId: '1:832443292148:web:458d4fafc07ad7f6e5c1a1',
    messagingSenderId: '832443292148',
    projectId: 'belajar-uts-9dd07',
    authDomain: 'belajar-uts-9dd07.firebaseapp.com',
    databaseURL: 'https://belajar-uts-9dd07-default-rtdb.firebaseio.com',
    storageBucket: 'belajar-uts-9dd07.firebasestorage.app',
    measurementId: 'G-K03HT4KE5B',
  );
}
