// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmVC5jUlJK4BzYIj5Jdt24eUsB_30v5eM',
    appId: '1:1025231319000:web:806f243f13a2b941890cad',
    messagingSenderId: '1025231319000',
    projectId: 'mdpgold-48985',
    authDomain: 'mdpgold-48985.firebaseapp.com',
    databaseURL: 'https://mdpgold-48985-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-48985.firebasestorage.app',
    measurementId: 'G-246LQJFC2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhco82cHcEgK_9DfKN3uFJ_ZiqR5Pp2yQ',
    appId: '1:1025231319000:android:3dbe123c1219a087890cad',
    messagingSenderId: '1025231319000',
    projectId: 'mdpgold-48985',
    databaseURL: 'https://mdpgold-48985-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-48985.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJdGO9QFMUG2arZP4CBqhRH35WyJHgtjg',
    appId: '1:1025231319000:ios:e01510ebee616dc1890cad',
    messagingSenderId: '1025231319000',
    projectId: 'mdpgold-48985',
    databaseURL: 'https://mdpgold-48985-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-48985.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJdGO9QFMUG2arZP4CBqhRH35WyJHgtjg',
    appId: '1:1025231319000:ios:e01510ebee616dc1890cad',
    messagingSenderId: '1025231319000',
    projectId: 'mdpgold-48985',
    databaseURL: 'https://mdpgold-48985-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-48985.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmVC5jUlJK4BzYIj5Jdt24eUsB_30v5eM',
    appId: '1:1025231319000:web:ccb588014ae1850c890cad',
    messagingSenderId: '1025231319000',
    projectId: 'mdpgold-48985',
    authDomain: 'mdpgold-48985.firebaseapp.com',
    databaseURL: 'https://mdpgold-48985-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-48985.firebasestorage.app',
    measurementId: 'G-WEBSS4EQVB',
  );

}